version: '3.8'

services:
  f5-tts-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: f5-tts-server:latest
    ports:
      - "8000:8000"
    volumes:
      - ./output:/app/output
      - ./uploads:/app/uploads
      - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s